### ISSUE TITLE
DL Track obsolete in light of new findings?

### ISSUE THREAD

**Issue by MartinLichtblau** [dfcf93/DeepLearningTREC2019#1]
@dfcf93 
Is the DL Track already running, or is it still in preparation? I ask, because I wanted to do similar research and just found out that in the light of new findings the question seems finally answered ‒ neural models are indeed better than non-neural models for IR.
One paper compared ~100 models using standard performance metrics on Robust04, concluding that neural models didn't catch up yet [1]. But around the same time in April new models have been published that surpass all others. They use language models like BERT and do full neural ranking, instead of re-ranking [2][3].
So isn't the question you and I are asking obsolete now? These recent findings even show that such models can make good use of large training sets.

See for yourself:
[1] [Critically Examining the “Neural Hype”: Weak Baselines and the Additivity of Effectiveness Gains from Neural Ranking Models](https://arxiv.org/pdf/1904.09171.pdf)

[2] [CEDR: Contextualized Embeddings for Document Ranking](https://arxiv.org/pdf/1904.07094v2.pdf)

[3] [Simple Applications of BERT for Ad Hoc Document Retrieval](https://arxiv.org/pdf/1903.10972.pdf)

[4] [An anatomy for neural search engines](https://www.semanticscholar.org/paper/An-anatomy-for-neural-search-engines-Nakamura-Calais/5727dc304715bf6f6e29694fad3bf870bac74fd8) _in depth about technical aspects and computing performance_

**Comment by dfcf93** [comment]
Hey!

We will be releasing the data shortly there has just been some delays in preperation.

Recent advances have definatley shown that Deep Learning is really efficient for IR and you need to go no further that look at the leaderboard on MSMARCO.org to confirm this. That being said we still have a long way to go to understand neural IR.  We want to explore how various models work together and how they work with weak suppervision.

**Comment by ArthurCamara** [comment]
I still think we have a lot of way to cover in this area. IR still haven't got the same level of improvement that computer vision had with CNNs or even NLP with transformers. 
Just check the first paper you cited. While there is some improvements, BM25 is still REALLY good at most ad-hoc retrieval tasks.

So, yeah, a TREC track like this is great for creating benchmarks and advance the deep IR field.
